import Home from '@/components/screens/nome/Home'
import { ICarData } from '@/interfaces/car.interface'
import { GetServerSideProps, GetStaticProps, NextPage } from 'next'
import api from '../../carbd/index'

const HomePage: NextPage<ICarData> = ({ cars }) => {
    return <Home cars={cars} />
}
// SSG
export const getStaticProps: GetStaticProps<ICarData> = async () => {
    const cars = await api.cars.fetchAll()
    return {
        props: { cars },
        revalidate: 60 // будет обновлятся кажые 60 ISR
    }
}

export default HomePage

// ===================== вариант из урока  SSR =======================
// import Home from '@/components/screens/nome/Home'
// import { ICarData } from '@/interfaces/car.interface'
// import { CarServise } from '@/services/car.service'
// import { GetServerSideProps, NextPage } from 'next'

// const HomePage: NextPage<ICarData> = ({ cars }) => {
//     return <Home cars={cars} />
// }

// export const getServerSideProps: GetServerSideProps<ICarData> = async () => {
//     const cars = await CarServise.getAll()
//     return {
//         props: { cars }
//     }
// }
// export default HomePage
// ======================================================================

//=========================== начало  ===================================

// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//     return (
//         <>
//             <Head>
//                 <title>Create next App</title>
//                 <meta
//                     name="description"
//                     content="Generated by create next App"
//                 />
//                 <meta
//                     name="viewport"
//                     content="width=divice-width, initial-scale=1"
//                 />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <main className={styles.main}>
//                 <div className={styles.description}>
//                     <p>
//                         Get started by editing&nbsp;
//                         <code className={styles.code}>src/app/page.tsx</code>
//                     </p>
//                     <div>
//                         <a
//                             href="https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
//                             target="_blank"
//                             rel="noopener noreferrer"
//                         >
//                             By{' '}
//                             <Image
//                                 src="/vercel.svg"
//                                 alt="Vercel Logo"
//                                 className={styles.vercelLogo}
//                                 width={100}
//                                 height={24}
//                                 priority
//                             />
//                         </a>
//                     </div>
//                 </div>

//                 <div className={styles.center}>
//                     <Image
//                         className={styles.logo}
//                         src="/next.svg"
//                         alt="Next.js Logo"
//                         width={180}
//                         height={37}
//                         priority
//                     />
//                 </div>

//                 <div className={styles.grid}>
//                     <a
//                         href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
//                         className={styles.card}
//                         target="_blank"
//                         rel="noopener noreferrer"
//                     >
//                         <h2>
//                             Docs <span>-&gt;</span>
//                         </h2>
//                         <p>
//                             Find in-depth information about Next.js features and
//                             API.
//                         </p>
//                     </a>

//                     <a
//                         href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
//                         className={styles.card}
//                         target="_blank"
//                         rel="noopener noreferrer"
//                     >
//                         <h2>
//                             Learn <span>-&gt;</span>
//                         </h2>
//                         <p>
//                             Learn about Next.js in an interactive course
//                             with&nbsp;quizzes!
//                         </p>
//                     </a>

//                     <a
//                         href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
//                         className={styles.card}
//                         target="_blank"
//                         rel="noopener noreferrer"
//                     >
//                         <h2>
//                             Templates <span>-&gt;</span>
//                         </h2>
//                         <p>Explore the Next.js 13 playground.</p>
//                     </a>

//                     <a
//                         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
//                         className={styles.card}
//                         target="_blank"
//                         rel="noopener noreferrer"
//                     >
//                         <h2>
//                             Deploy <span>-&gt;</span>
//                         </h2>
//                         <p>
//                             Instantly deploy your Next.js site to a shareable
//                             URL with Vercel.
//                         </p>
//                     </a>
//                 </div>
//             </main>
//         </>
//     )
// }
